### ISSUE TITLE
Log volume out of disk leads to "Segfault detected, aborting process"

### ISSUE THREAD

**Issue by k-wall** [ozangunalp/kafka-native#151]
I just hit a segfault when using the new Kafka 3.7 image.

[out.txt](https://github.com/ozangunalp/kafka-native/files/14432799/out.txt)

LogSegment was one of the areas changed by #148.

```
2024-02-28 10:34:18 Stacktrace for the failing thread 0x00007f7f00000b80:
2024-02-28 10:34:18   SP 0x00007f7f24ff8630 IP 0x0000000000dfe2f1  com.oracle.svm.core.code.CodeInfo@0x7f8019a6c8d8 name = image code
2024-02-28 10:34:18   SP 0x00007f7f24ff8650 IP 0x00000000023fae7e  [image code] org.apache.kafka.storage.internals.log.OffsetIndex.append(OffsetIndex.java:151)
2024-02-28 10:34:18   SP 0x00007f7f24ff86b0 IP 0x00000000023e6597  [image code] org.apache.kafka.storage.internals.log.LogSegment.append(LogSegment.java:267)
2024-02-28 10:34:18   SP 0x00007f7f24ff8740 IP 0x000000000151e106  [image code] kafka.log.LocalLog.append(LocalLog.scala:410)
2024-02-28 10:34:18   SP 0x00007f7f24ff8780 IP 0x0000000001595c4d  [image code] kafka.log.UnifiedLog.append(UnifiedLog.scala:906)
2024-02-28 10:34:18   SP 0x00007f7f24ff8890 IP 0x00000000015990ec  [image code] kafka.log.UnifiedLog.appendAsLeader(UnifiedLog.scala:722)
2024-02-28 10:34:18   SP 0x00007f7f24ff88f0 IP 0x000000000134655b  [image code] kafka.cluster.Partition.$anonfun$appendRecordsToLeader$1(Partition.scala:1364)
2024-02-28 10:34:18   SP 0x00007f7f24ff8970 IP 0x000000000135a676  [image code] kafka.cluster.Partition.appendRecordsToLeader(Partition.scala:1352)
2024-02-28 10:34:18   SP 0x00007f7f24ff89d0 IP 0x0000000001838ed0  [image code] kafka.server.ReplicaManager.$anonfun$appendToLocalLog$6(ReplicaManager.scala:1529)
2024-02-28 10:34:18   SP 0x00007f7f24ff8a80 IP 0x00000000018327c9  [image code] kafka.server.ReplicaManager$$Lambda$f4a93bcaae8878dda4af003cd9ae7d643a6b6b6f.apply(Unknown Source)
2024-02-28 10:34:18   SP 0x00007f7f24ff8aa0 IP 0x0000000002d32b73  [image code] scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:28)
2024-02-28 10:34:18   SP 0x00007f7f24ff8b00 IP 0x00000000026b0753  [image code] scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:27)
2024-02-28 10:34:18   SP 0x00007f7f24ff8b00 IP 0x00000000026b0753  [image code] scala.collection.mutable.HashMap.map(HashMap.scala:35)
2024-02-28 10:34:18   SP 0x00007f7f24ff8b10 IP 0x00000000018619f1  [image code] kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:1515)
2024-02-28 10:34:18   SP 0x00007f7f24ff8b60 IP 0x0000000001860c0b  [image code] kafka.server.ReplicaManager.appendRecords(ReplicaManager.scala:860)
2024-02-28 10:34:18   SP 0x00007f7f24ff8c40 IP 0x00000000017a32d3  [image code] kafka.server.KafkaApis.handleProduceRequest(KafkaApis.scala:720)
2024-02-28 10:34:18   SP 0x00007f7f24ff8d20 IP 0x0000000001784dfd  [image code] kafka.server.KafkaApis.handle(KafkaApis.scala:184)
2024-02-28 10:34:18   SP 0x00007f7f24ff8d80 IP 0x00000000017dcac1  [image code] kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:160)
2024-02-28 10:34:18   SP 0x00007f7f24ff8e40 IP 0x0000000000c848b4  [image code] java.lang.Thread.run(Thread.java:833)
2024-02-28 10:34:18   SP 0x00007f7f24ff8e50 IP 0x000000000083982d  [image code] com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
2024-02-28 10:34:18   SP 0x00007f7f24ff8e80 IP 0x0000000000803827  [image code] com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
2024-02-28 10:34:18   SP 0x00007f7f24ff8ea0 IP 0x00000000007592bf  [image code] com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_cf47bd191b082a3631657d369b9255c828b9a95c(IsolateEnterStub.java:0)
2024-02-28 10:34:18
```

**Comment by ozangunalp** [comment]
Looking at the stacktrace it happens accessing the `MappedByteBuffer`

**Comment by ozangunalp** [comment]
With which --throughput ?

**Comment by ozangunalp** [comment]
@k-wall we can also test the #150 against your scenario if it fixes the issue

**Comment by k-wall** [comment]
like this: 

```
 bin/kafka-producer-perf-test.sh --topic ${TOPIC} --throughput -1 --num-records ${NUM_RECORDS} --record-size ${RECORD_SIZE} \
      --producer-props acks=all bootstrap.servers=${ENDPOINT} 
```

**Comment by k-wall** [comment]
> Looking at the stacktrace it happens accessing the MappedByteBuffer

I don't see changes in the way that MappedByteBuffer is handled in 3.7.0

> @k-wall we can also test the https://github.com/ozangunalp/kafka-native/pull/150 against your scenario if it fixes the issue

Yes, I'll do that.

**Comment by ozangunalp** [comment]
I couldn't reproduce it in the first run. Running a single node on podman.

**Comment by k-wall** [comment]
The container is running out of diskspace. The same behaviour happens on the old image 3.6.1 if I increase the number of messages.  It seems the disk utilisation is slightly different.

This will reproduce it:


```yaml
version: '3.5'

name: kafka-native
services:
  broker1:
    storage_opt:
      size: '1G'
    image: quay.io/ogunalp/kafka-native:latest-kafka-3.6.1
    ports:
      - "9095:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9095
      SERVER_HOST: broker1
      KAFKA_BROKER_ID: 1
      SERVER_CLUSTER_ID: BmMQZPq6Qoua1-yvgGJFbA
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:9094
    networks:
      - kafka-network
networks:
  kafka-network:
    name: kafka-native
```

```bash
docker run --network kafka-native --rm quay.io/strimzi/kafka:0.39.0-kafka-3.6.1 bin/kafka-producer-perf-test.sh  --topic foo --throughput -1 --num-records 20000000 --record-size 1024   --producer-props acks=all bootstrap.servers=broker1:9093
```

I would expect an exception to bring the broker down when the disk space fills up, so it is not clear why it isn't happening in this case.

I'll have a dig soon.

**Comment by k-wall** [comment]
Odd, I'm now failing to reproduce the issue at all. The VM of my Docker had almost run up against its virtual disk limit, so I'm wonder if that had an effect on things? I've since cleanup up my Docker environment.

Trying now with a constrained kafka.log.dir shows no sign of a general problem:

```
version: '3.5'

name: kafka-native
services:
  broker1:
    storage_opt:
      size: '1G'
    image: quay.io/ogunalp/kafka-native:latest-kafka-3.7.0
    ports:
      - "9095:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9095
      KAFKA_LOG_DIR: /tiny
      SERVER_HOST: broker1
      KAFKA_BROKER_ID: 1
      SERVER_CLUSTER_ID: BmMQZPq6Qoua1-yvgGJFbA
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:9094
    networks:
      - kafka-network
    volumes:
    - type: tmpfs
      target: /tiny
      tmpfs:
        size: "3221225472"
networks:
  kafka-network:
    name: kafka-native
```

It fails in the expected way when the disk fills up:

```
kafka-native-broker1-1  | 2024-03-08 16:42:33,730 ERROR [org.apa.kaf.sto.int.log.LogDirFailureChannel] (data-plane-kafka-request-handler-6) Error while appending records to foo-0 in dir /tiny: java.io.IOException: No space left on device
kafka-native-broker1-1  | 	at java.base@17.0.8/sun.nio.ch.FileDispatcherImpl.write0(FileDispatcherImpl.java)
kafka-native-broker1-1  | 	at java.base@17.0.8/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
kafka-native-broker1-1  | 	at java.base@17.0.8/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
kafka-native-broker1-1  | 	at java.base@17.0.8/sun.nio.ch.IOUtil.write(IOUtil.java:97)
kafka-native-broker1-1  | 	at java.base@17.0.8/sun.nio.ch.IOUtil.write(IOUtil.java:67)
kafka-native-broker1-1  | 	at java.base@17.0.8/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288)
kafka-native-broker1-1  | 	at org.apache.kafka.common.record.MemoryRecords.writeFullyTo(MemoryRecords.java:90)
kafka-native-broker1-1  | 	at org.apache.kafka.common.record.FileRecords.append(FileRecords.java:188)
kafka-native-broker1-1  | 	at org.apache.kafka.storage.internals.log.LogSegment.append(LogSegment.java:259)
kafka-native-broker1-1  | 	at kafka.log.LocalLog.append(LocalLog.scala:410)
kafka-native-broker1-1  | 	at kafka.log.UnifiedLog.append(UnifiedLog.scala:906)
kafka-native-broker1-1  | 	at kafka.log.UnifiedLog.appendAsLeader(UnifiedLog.scala:722)
kafka-native-broker1-1  | 	at kafka.cluster.Partition.$anonfun$appendRecordsToLeader$1(Partition.scala:1364)
kafka-native-broker1-1  | 	at kafka.cluster.Partition.appendRecordsToLeader(Partition.scala:1352)
kafka-native-broker1-1  | 	at kafka.server.ReplicaManager.$anonfun$appendToLocalLog$6(ReplicaManager.scala:1529)
kafka-native-broker1-1  | 	at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:28)
kafka-native-broker1-1  | 	at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:27)
kafka-native-broker1-1  | 	at scala.collection.mutable.HashMap.map(HashMap.scala:35)
kafka-native-broker1-1  | 	at kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:1515)
kafka-native-broker1-1  | 	at kafka.server.ReplicaManager.appendRecords(ReplicaManager.scala:860)
kafka-native-broker1-1  | 	at kafka.server.KafkaApis.handleProduceRequest(KafkaApis.scala:720)
kafka-native-broker1-1  | 	at kafka.server.KafkaApis.handle(KafkaApis.scala:184)
kafka-native-broker1-1  | 	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:160)
kafka-native-broker1-1  | 	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
kafka-native-broker1-1  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
kafka-native-broker1-1  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

I'll close this issue.
