### ISSUE TITLE
File failed to get deleted

### ISSUE THREAD

**Issue by showuon** [ozangunalp/kafka-native#228]
See the errors while running perf test in kroxylicious, and then files stayed in file system, which caused disk full in the end.
This is tested in `quay.io/ogunalp/kafka-native:latest-kafka-3.8.0` image.
```
2024-09-10 03:40:14,138 INFO  [org.apa.kaf.sto.int.log.LogSegment] (kafka-scheduler-6) Deleted log /work/./target/log-dir/perf-test-18997-0.7109edb31fa540cab275cf9089bd02c3-delete/00000000000000000000.log.deleted.
2024-09-10 03:40:14,138 INFO  [org.apa.kaf.sto.int.log.LogSegment] (kafka-scheduler-6) Deleted offset index /work/./target/log-dir/perf-test-18997-0.7109edb31fa540cab275cf9089bd02c3-delete/00000000000000000000.index.deleted.
2024-09-10 03:40:14,139 INFO  [org.apa.kaf.sto.int.log.LogSegment] (kafka-scheduler-6) Deleted time index /work/./target/log-dir/perf-test-18997-0.7109edb31fa540cab275cf9089bd02c3-delete/00000000000000000000.timeindex.deleted.
2024-09-10 03:40:14,139 ERROR [kaf.log.LogManager] (kafka-scheduler-6) Exception in kafka-delete-logs thread.: java.lang.NullPointerException
	at org.apache.kafka.storage.internals.log.LogSegment.deleteTypeIfExists(LogSegment.java:818)
	at org.apache.kafka.storage.internals.log.LogSegment.lambda$deleteIfExists$13(LogSegment.java:794)
	at org.apache.kafka.common.utils.Utils.tryAll(Utils.java:1168)
	at org.apache.kafka.storage.internals.log.LogSegment.deleteIfExists(LogSegment.java:790)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$5(LocalLog.scala:927)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$5$adapted(LocalLog.scala:926)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$4(LocalLog.scala:926)
	at kafka.log.LocalLog$.deleteSegments$1(LocalLog.scala:716)
	at kafka.log.LocalLog$.deleteSegmentFiles(LocalLog.scala:935)
	at kafka.log.LocalLog.removeAndDeleteSegments(LocalLog.scala:289)
	at kafka.log.LocalLog.$anonfun$deleteAllSegments$2(LocalLog.scala:254)
	at kafka.log.LocalLog.deleteAllSegments(LocalLog.scala:716)
	at kafka.log.UnifiedLog.$anonfun$delete$2(UnifiedLog.scala:1743)
	at kafka.log.UnifiedLog.delete(UnifiedLog.scala:1922)
	at kafka.log.LogManager.deleteLogs(LogManager.scala:1159)
	at kafka.log.LogManager.$anonfun$deleteLogs$6(LogManager.scala:1173)
	at org.apache.kafka.server.util.KafkaScheduler.lambda$schedule$1(KafkaScheduler.java:150)
	at java.base@17.0.12/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base@17.0.12/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.12/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base@17.0.12/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.12/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.12/java.lang.Thread.run(Thread.java:840)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:885)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:860)
```

Detail can be found here: https://github.com/kroxylicious/kroxylicious/pull/1505

**Comment by k-wall** [comment]
I think I see the issue.

https://github.com/ozangunalp/kafka-native/blob/4006af676a8187516b3c92eb75369e340f40f7d0/quarkus-kafka-server-extension/deployment/src/main/java/com/ozangunalp/kafka/server/extension/deployment/KafkaServerExtensionProcessor.java#L340

I think that code is overwriting the class's initialisation.   It is failing to PUTSTATIC for the static field introduced [KAFKA-16424](https://issues.apache.org/jira/browse/KAFKA-16424)[:](https://github.com/apache/kafka/commit/a38185280ca011d4caced05171e94ac53cda964d).  So the upshot is, that field is NPE

I think that explains the NPE.

**Comment by ozangunalp** [comment]
Absolutely. Maybe we can get rid of those substitutions.

**Comment by k-wall** [comment]
I don't have any skills in ASM, so I wouldn't really know where to start with an alternative approach.
